version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    interval: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.1
    - 1.4.2
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
  - dependency-name: pytest
    versions:
    - 6.2.2
