[tool.poetry]
name = "app"
version = "2.7.1"
description = "App to manage garments"
authors = ["José Ignacio Amelivia Santiago <hello@namelivia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "*"
uvicorn = "*"
python-multipart = "*"
sqlalchemy = "*"
psycopg2-binary = "*"
requests = "*"
alembic = "*"
sqlalchemy-utils = "*"
typing-inspect = "*"
gunicorn = "*"
uvloop = "*"
httptools = "*"
httpx = "~0.27.0"
cryptography = "*"
fastapi-utils = "*"
pyjwt = { git = "https://github.com/jpadilla/pyjwt.git", rev = "master" }

[tool.poetry.dev-dependencies]
pytest = "*"
mock = "*"
pytest-cov = "*"
pudb = "*"
codecov = "*"
black = "*"
pre-commit = "*"
pytest-freezegun = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
