"""Add total times worn column

Revision ID: 07d2a9135ff7
Revises: f7c28148a512
Create Date: 2021-04-01 09:03:12.670755

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07d2a9135ff7"
down_revision = "f7c28148a512"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("total_worn", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("total_worn")

    # ### end Alembic commands ###
