"""Add multiple activities for garment

Revision ID: 0c1f10b42c4b
Revises: 36612cfdeb12
Create Date: 2024-04-18 17:19:19.513932

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c1f10b42c4b"
down_revision = "36612cfdeb12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garment_activity",
        sa.Column("garment_id", sa.Integer(), nullable=True),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["garment_id"],
            ["garments.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("garment_activity")
    # ### end Alembic commands ###
