"""Create garment_types table

Revision ID: 24299f16af9d
Revises: c03db4f3f114
Create Date: 2021-01-20 20:36:58.988460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24299f16af9d"
down_revision = "c03db4f3f114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garment_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("garment_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_garment_types_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garment_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_garment_types_id"))

    op.drop_table("garment_types")
    # ### end Alembic commands ###
