"""Add worn integer

Revision ID: 258f3c76655b
Revises: 24299f16af9d
Create Date: 2021-03-17 14:15:23.714760

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "258f3c76655b"
down_revision = "24299f16af9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("worn", sa.Integer(), nullable=False, server_default="3")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("worn")

    # ### end Alembic commands ###
