"""add_weather_to_activity_garment_type_table

Revision ID: 333483446510
Revises: c3f618e42e63
Create Date: 2024-06-08 22:28:04.222096

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "333483446510"
down_revision = "c3f618e42e63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_garment_type", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("weather", sa.String(), nullable=False, server_default="cold")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_garment_type", schema=None) as batch_op:
        batch_op.drop_column("weather")

    # ### end Alembic commands ###
