"""Add activities to outfits

Revision ID: 36612cfdeb12
Revises: d3bcba08d23b
Create Date: 2024-04-18 16:38:57.808909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36612cfdeb12"
down_revision = "d3bcba08d23b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("activity", sa.String(), nullable=False, server_default="None")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.drop_column("activity")

    # ### end Alembic commands ###
