"""create_activities_table

Revision ID: 405ab8fe4c57
Revises: b05a649da764
Create Date: 2022-04-05 08:42:11.326541

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "405ab8fe4c57"
down_revision = "b05a649da764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activities_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_id"))

    op.drop_table("activities")
    # ### end Alembic commands ###
