"""Add garment types to activities

Revision ID: 76bdbd4b31be
Revises: 0c1f10b42c4b
Create Date: 2024-04-19 08:08:03.528422

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76bdbd4b31be"
down_revision = "0c1f10b42c4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_garment_type",
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("garment_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["garment_type_id"],
            ["garment_types.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_garment_type")
    # ### end Alembic commands ###
