"""Add times rejected to garments

Revision ID: 7c8caa679f4b
Revises: 76bdbd4b31be
Create Date: 2024-04-19 16:04:27.684540

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c8caa679f4b"
down_revision = "76bdbd4b31be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "times_rejected", sa.Integer(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("times_rejected")

    # ### end Alembic commands ###
