"""add_thrown_away_boolean

Revision ID: 82021d68d4a3
Revises: 07d2a9135ff7
Create Date: 2022-03-13 11:57:05.879080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82021d68d4a3"
down_revision = "07d2a9135ff7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "thrown_away", sa.Boolean(), nullable=False, server_default="FALSE"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("thrown_away")

    # ### end Alembic commands ###
