"""Create user_data table

Revision ID: 87a547550402
Revises: a949c738f2ec
Create Date: 2021-01-18 15:21:48.681619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87a547550402"
down_revision = "a949c738f2ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
