"""add_wear_to_wash

Revision ID: 938a751b70ed
Revises: 258f3c76655b
Create Date: 2021-03-17 16:29:52.144730

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "938a751b70ed"
down_revision = "258f3c76655b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("wear_to_wash", sa.Integer(), nullable=False, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("wear_to_wash")

    # ### end Alembic commands ###
