"""Create places table

Revision ID: 9887ceebcaa8
Revises: ac6717d45ff4
Create Date: 2021-01-18 09:42:39.586946

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9887ceebcaa8"
down_revision = "ac6717d45ff4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
