"""Create places table

Revision ID: a949c738f2ec
Revises: 9887ceebcaa8
Create Date: 2021-01-18 09:44:58.464551

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a949c738f2ec"
down_revision = "9887ceebcaa8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_places_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_places_id"))

    op.drop_table("places")
    # ### end Alembic commands ###
