"""Add place to garment

Revision ID: ac6717d45ff4
Revises: 03fb00023626
Create Date: 2021-01-17 18:18:43.484598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac6717d45ff4"
down_revision = "03fb00023626"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("place", sa.String(), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("place")

    # ### end Alembic commands ###
