"""add_activities_to_garments

Revision ID: b05a649da764
Revises: 82021d68d4a3
Create Date: 2022-03-29 17:18:12.900122

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b05a649da764"
down_revision = "82021d68d4a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activity", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.drop_column("activity")

    # ### end Alembic commands ###
