"""add_weather_to_outfits

Revision ID: bbda42584fec
Revises: ef39f3764f68
Create Date: 2024-06-10 14:27:07.350842

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bbda42584fec"
down_revision = "ef39f3764f68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("weather", sa.String(), nullable=False, server_default="cold")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.drop_column("weather")

    # ### end Alembic commands ###
