"""Create user_data table

Revision ID: c03db4f3f114
Revises: 87a547550402
Create Date: 2021-01-18 16:24:30.154784

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c03db4f3f114"
down_revision = "87a547550402"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("place", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_data_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_data_id"))

    op.drop_table("user_data")
    # ### end Alembic commands ###
