"""make_activity_not_nullable

Revision ID: c03e07f97cc8
Revises: 405ab8fe4c57
Create Date: 2024-03-08 08:23:57.120482

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c03e07f97cc8"
down_revision = "405ab8fe4c57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.alter_column("activity", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garments", schema=None) as batch_op:
        batch_op.alter_column("activity", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
