"""Add lat long to places

Revision ID: c3f618e42e63
Revises: 7c8caa679f4b
Create Date: 2024-05-18 19:57:34.153190

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3f618e42e63"
down_revision = "7c8caa679f4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("latitude", sa.String(), nullable=False, server_default="0.0")
        )
        batch_op.add_column(
            sa.Column("longitude", sa.String(), nullable=False, server_default="0.0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")

    # ### end Alembic commands ###
