"""Add worn on to outfit

Revision ID: d3bcba08d23b
Revises: f3e0b4035739
Create Date: 2024-04-11 22:49:53.435444

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3bcba08d23b"
down_revision = "f3e0b4035739"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("worn_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.drop_column("worn_on")

    # ### end Alembic commands ###
