"""add_outfits_table

Revision ID: db233d85b7c5
Revises: c03e07f97cc8
Create Date: 2024-03-08 08:33:34.823377

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db233d85b7c5"
down_revision = "c03e07f97cc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outfits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outfits_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outfits_id"))

    op.drop_table("outfits")
    # ### end Alembic commands ###
