"""add_outfit_garments_table

Revision ID: f3e0b4035739
Revises: db233d85b7c5
Create Date: 2024-03-08 11:36:30.963547

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3e0b4035739"
down_revision = "db233d85b7c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outfit_garment",
        sa.Column("outfit_id", sa.Integer(), nullable=True),
        sa.Column("garment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["garment_id"],
            ["garments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["outfit_id"],
            ["outfits.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outfit_garment")
    # ### end Alembic commands ###
